# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lge/msm8998-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter joan l01k phoenix_sprout q910,$(TARGET_DEVICE)),)

endif
